# Generated by Django 5.2.7 on 2025-10-31 13:30

from django.db import migrations, models


def populate_full_address(apps, schema_editor):
    Address = apps.get_model("invoices", "Address")
    for address in Address.objects.all():
        parts = []
        if address.street:
            parts.append(address.street)
        line_two_parts = []
        if address.postal_code:
            line_two_parts.append(address.postal_code)
        if address.city:
            line_two_parts.append(address.city)
        line_two = " ".join(line_two_parts).strip()
        if line_two:
            parts.append(line_two)
        region_parts = []
        if address.state:
            region_parts.append(address.state)
        if address.country:
            region_parts.append(address.country)
        region_line = " ".join(region_parts).strip()
        if region_line:
            parts.append(region_line)
        combined = "\n".join(part for part in parts if part)
        if combined:
            address.full_address = combined
            address.save(update_fields=["full_address"])


def clear_full_address(apps, schema_editor):
    Address = apps.get_model("invoices", "Address")
    Address.objects.all().update(full_address=None)


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0023_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="full_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(populate_full_address, clear_full_address),
    ]
