# Generated by Django 5.2.7 on 2025-10-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0024_address_full_address_alter_address_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="payment_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_terms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
