# Generated by Django 5.2.7 on 2025-10-31 13:53

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_customers(apps, schema_editor):
    Customer = apps.get_model('invoices', 'Customer')
    GlobalSettings = apps.get_model('invoices', 'GlobalSettings')
    Issuer = apps.get_model('invoices', 'Issuer')

    issuer = None

    global_settings = GlobalSettings.objects.select_related('issuer').first()
    if global_settings and global_settings.issuer:
        issuer = global_settings.issuer
    else:
        issuer = Issuer.objects.first()

    if issuer:
        Customer.objects.filter(issuer__isnull=True).update(issuer=issuer)


def noop_reverse(apps, schema_editor):
    # No-op reverse migration: keeping issuer references is fine when rolling back schema
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0025_company_payment_method_company_payment_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="issuer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="invoices.issuer",
            ),
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="issuer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="invoices.issuer",
            ),
        ),
        migrations.AlterField(
            model_name="issuer",
            name="company",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issuer_profile",
                to="invoices.company",
            ),
        ),
        migrations.RunPython(assign_existing_customers, noop_reverse),
    ]
