# Generated by Django 5.2.7 on 2025-10-31 14:35

from django.db import migrations, models


def populate_description_from_product(apps, schema_editor):
    OrderLine = apps.get_model('invoices', 'OrderLine')
    Product = apps.get_model('invoices', 'Product')

    for order_line in OrderLine.objects.exclude(product__isnull=True):
        product = Product.objects.filter(pk=order_line.product_id).first()
        if product and product.name:
            OrderLine.objects.filter(pk=order_line.pk).update(description=product.name)


def noop_reverse(apps, schema_editor):
    pass


def normalize_orderline_decimals(apps, schema_editor):
    from decimal import Decimal, InvalidOperation

    OrderLine = apps.get_model('invoices', 'OrderLine')

    for order_line in OrderLine.objects.all():
        quantity = order_line.quantity
        unit_price = order_line.unit_price
        line_total = order_line.line_total

        def _convert(value):
            if value in (None, ''):
                return Decimal('0')
            try:
                return Decimal(str(value))
            except (InvalidOperation, TypeError, ValueError):
                return Decimal('0')

        normalized_quantity = _convert(quantity)
        normalized_unit_price = _convert(unit_price)
        normalized_line_total = normalized_quantity * normalized_unit_price if line_total in (None, '') else _convert(line_total)

        OrderLine.objects.filter(pk=order_line.pk).update(
            quantity=normalized_quantity,
            unit_price=normalized_unit_price,
            line_total=normalized_line_total,
        )


def normalize_invoice_decimals(apps, schema_editor):
    from decimal import Decimal, InvalidOperation

    Invoice = apps.get_model('invoices', 'Invoice')

    def _convert(value):
        if value in (None, ''):
            return Decimal('0')
        try:
            return Decimal(str(value))
        except (InvalidOperation, TypeError, ValueError):
            return Decimal('0')

    fields = [
        'discount_value',
        'discount_amount',
        'sub_total',
        'tax_base',
        'tax_value',
        'tax_amount',
        'total_due',
    ]

    for invoice in Invoice.objects.all():
        update_kwargs = {}
        for field in fields:
            update_kwargs[field] = _convert(getattr(invoice, field))
        Invoice.objects.filter(pk=invoice.pk).update(**update_kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0027_project_invoice_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(populate_description_from_product, noop_reverse),
        migrations.RunPython(normalize_orderline_decimals, noop_reverse),
        migrations.RunPython(normalize_invoice_decimals, noop_reverse),
        migrations.RemoveField(
            model_name="orderline",
            name="product",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
