# Generated by Django 5.2.7 on 2025-10-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0029_normalize_decimal_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="discount_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="sub_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_base",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_due",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="line_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
