# Generated by Django 5.2.7 on 2025-10-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0030_alter_invoice_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("invoiced", "Invoiced"),
                    ("pending_payment", "Pending Payment"),
                    ("overdue", "Overdue"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
