# Generated by Django 5.2.7 on 2025-10-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0032_update_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("invoiced", "Invoiced"),
                    ("overdue", "Overdue"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
