# Generated by Django 5.2.7 on 2025-11-01 11:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0035_invoicefilterview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(blank=True, max_length=32)),
                ("symbol", models.CharField(blank=True, max_length=8)),
                (
                    "exchange_rate_to_base",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("is_base", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("use_retainer", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("days", models.PositiveIntegerField(default=30)),
                ("description", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "ordering": ["days", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="orderline",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="external_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="base_currency_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                default=Decimal("1"),
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="external_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reference_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="invoice",
            name="secondary_tax_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="invoice",
            name="secondary_tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="template_identifier",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="invoice",
            name="uses_secondary_tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderline",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderline",
            name="external_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("time", "Time"),
                    ("flat", "Flat Fee"),
                    ("quantity", "Quantity"),
                    ("expense", "Expense"),
                ],
                default="quantity",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="manual_total",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderline",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="time_entry_external_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="orderline",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="billing_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="external_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="invoices.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="line_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="invoices.currency",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="invoices.currency",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        default=Decimal("1"),
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "base_currency_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("received_at", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("applied", "Applied")],
                        default="applied",
                        max_length=16,
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="invoices.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.customer",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.issuer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="invoices.project",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="invoices.paymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="invoices.paymentterm",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="invoices.paymentterm",
            ),
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("statement_number", models.CharField(blank=True, max_length=64)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                ("sent_date", models.DateField(blank=True, null=True)),
                (
                    "total_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "current_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "overdue_30",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "overdue_60",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "overdue_90",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "overdue_over_90",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="invoices.customer",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="invoices.issuer",
                    ),
                ),
            ],
            options={
                "ordering": ["-from_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_applied",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_applications",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="invoices.payment",
                    ),
                ),
            ],
            options={
                "unique_together": {("payment", "invoice")},
            },
        ),
    ]
