# Generated by Django 5.2.7 on 2025-11-01 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0036_currency_paymentmethod_paymentterm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="invoices.invoice"
            ),
        ),
    ]
