# Generated by Django 5.2.7 on 2025-11-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0037_alter_orderline_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="global_settings",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="mail_info",
        ),
        migrations.DeleteModel(
            name="GlobalSettings",
        ),
        migrations.DeleteModel(
            name="MailInfo",
        ),
    ]
