# Generated by Django 5.2.7 on 2025-11-01 12:56

from django.db import migrations, models


def copy_contact_details(apps, schema_editor):
    Company = apps.get_model("invoices", "Company")
    Contact = apps.get_model("invoices", "Contact")

    for company in Company.objects.select_related("contact"):
        contact = getattr(company, "contact", None)
        if not contact:
            continue
        updated_fields = []
        if contact.name and company.contact_name != contact.name:
            company.contact_name = contact.name
            updated_fields.append("contact_name")
        if contact.email and company.contact_email != contact.email:
            company.contact_email = contact.email
            updated_fields.append("contact_email")
        if contact.cc_email and company.contact_cc_email != contact.cc_email:
            company.contact_cc_email = contact.cc_email
            updated_fields.append("contact_cc_email")
        if contact.phone_number and company.contact_phone_number != contact.phone_number:
            company.contact_phone_number = contact.phone_number
            updated_fields.append("contact_phone_number")
        if contact.country and company.contact_country != contact.country:
            company.contact_country = contact.country
            updated_fields.append("contact_country")
        if updated_fields:
            company.save(update_fields=updated_fields)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0038_remove_invoice_global_settings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contact_cc_email",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_email",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_phone_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(copy_contact_details, noop),
        migrations.RemoveField(
            model_name="company",
            name="contact",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
