# Generated by Django 5.2.7 on 2025-11-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0039_remove_company_contact_company_contact_cc_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="method",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
