# Generated by Django 5.2.7 on 2025-11-01 13:42

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Max


def populate_invoice_settings(apps, schema_editor):
    Issuer = apps.get_model("invoices", "Issuer")
    Invoice = apps.get_model("invoices", "Invoice")

    for issuer in Issuer.objects.all():
        max_number = (
            Invoice.objects.filter(issuer=issuer).aggregate(Max("number")).get("number__max") or 0
        )
        next_number = max_number + 1 if max_number >= 0 else 1

        fields_to_update = []

        if not issuer.invoice_format:
            issuer.invoice_format = "{{YYYY}}.{{ID}}"
            fields_to_update.append("invoice_format")

        if issuer.next_invoice_number != next_number:
            issuer.next_invoice_number = next_number
            fields_to_update.append("next_invoice_number")

        if fields_to_update:
            issuer.save(update_fields=fields_to_update)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0040_remove_payment_method_delete_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issuing_companies",
                to="invoices.paymentterm",
            ),
        ),
        migrations.AddField(
            model_name="issuer",
            name="invoice_format",
            field=models.CharField(default="{{YYYY}}.{{ID}}", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issuer",
            name="next_invoice_number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RunPython(populate_invoice_settings, noop),
    ]
