# Generated by Django 5.2.7 on 2025-11-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0041_company_payment_term_issuer_invoice_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuer",
            name="invoice_format",
            field=models.CharField(default="{{YYYY}}.{{ID}}", max_length=64),
        ),
        migrations.AlterField(
            model_name="issuer",
            name="next_invoice_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
