# Generated by Django 5.2.7 on 2025-11-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0042_alter_issuer_invoice_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
