# Generated by Django 5.2.7 on 2025-11-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0043_alter_company_bank_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="customer_information_file_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
