# Generated by Django 5.2.7 on 2025-11-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0050_wise_expense_import"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoices_in_project_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoices_in_customer_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoices_in_project_issued_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoices_in_customer_issued_idx",
        ),
    ]
