# Generated by Django 5.2.7 on 2025-11-07 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0053_backfill_expense_memo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issuer",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users permitted to access this issuer.",
                related_name="issuers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
