# Generated by Django 5.2.7 on 2025-12-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0054_issuer_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
