# Generated by Django 5.2.7 on 2025-12-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("invoices", "0055_invoice_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="default_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_profiles",
                to="invoices.company",
            ),
        ),
    ]

